const defaultType = [
  {id: "-1", type: "pay", name: "餐饮", icon: "rest"},
  {id: "-2", type: "pay", name: "衣服", icon: "clothes"},
  {id: "-3", type: "pay", name: "书", icon: "books"},
  {id: "-4", type: "pay", name: "购物", icon: "shopping"},
  {id: "-5", type: "pay", name: "数码", icon: "digital"},
  {id: "-6", type: "pay", name: "住房", icon: "rent"},
  {id: "-7", type: "pay", name: "交通", icon: "traffic"},
  {id: "-8", type: "pay", name: "话费", icon: "phone-bill"},
  {id: "-9", type: "pay", name: "买菜", icon: "vegetables"},
  {id: "-10", type: "pay", name: "宠物", icon: "pets"},
  {id: "-11", type: "pay", name: "水电", icon: "ew-cost"},
  {id: "-12", type: "income", name: "工资", icon: "wages"},
  {id: "-13", type: "income", name: "兼职", icon: "part-time"},
  {id: "-14", type: "income", name: "理财", icon: "financial"},
  {id: "-15", type: "income", name: "闲置", icon: "idle"},
  {id: "-16", type: "pay", name: "娱乐", icon: "entertainment"},
  {id: "-17", type: "pay", name: "外卖", icon: "take-out"},
  {id: "-18", type: "pay", name: "医疗", icon: "medical-care"},
  {id: "-19", type: "pay", name: "旅游", icon: "travel"},
  {id: "-20", type: "pay", name: "其他", icon: "other"},
  {id: "-21", type: "income", name: "其他", icon: "other"},
];

export default defaultType;
